# SPDX-License-Identifier: Apache-2.0
"""ALGORITHM_REGISTRY: single source of truth for available algorithms (metadata)."""

ALGORITHM_REGISTRY: dict[str, dict] = {
    "descriptive_statistics": {
        "name": "Descriptive Statistics",
        "description": "Mean, Std Dev, Variance, Min/Max, IQR approximation, Skewness.",
        "required_columns": 1,
        "column_types": ["float", "integer"],
        "parameters": {},
        "estimated_seconds": 2,
        "approximation_warning": "Min/Max and IQR are approximations (no sorting in HE).",
        "clinical_use_case": "First data exploration in clinical studies.",
    },
    "correlation": {
        "name": "Correlation Analysis",
        "description": "Pearson correlation between two columns.",
        "required_columns": 2,
        "column_types": ["float", "integer"],
        "parameters": {},
        "estimated_seconds": 2,
        "approximation_warning": None,
        "clinical_use_case": "Association between two continuous markers.",
    },
    "group_comparison": {
        "name": "Group Comparison (t-Test)",
        "description": "Compare two groups (first vs second half of data).",
        "required_columns": 1,
        "column_types": ["float", "integer"],
        "parameters": {},
        "estimated_seconds": 2,
        "approximation_warning": "Groups are index-based (no categorical column in HE).",
        "clinical_use_case": "Treatment vs control comparison.",
    },
    "linear_regression": {
        "name": "Linear Regression",
        "description": "Slope and intercept for one predictor and one target.",
        "required_columns": 2,
        "column_types": ["float", "integer"],
        "parameters": {},
        "estimated_seconds": 2,
        "approximation_warning": None,
        "clinical_use_case": "Predict one variable from another.",
    },
    "distribution": {
        "name": "Distribution Overview",
        "description": "Histogram approximation (5 buckets by index).",
        "required_columns": 1,
        "column_types": ["float", "integer"],
        "parameters": {},
        "estimated_seconds": 1,
        "approximation_warning": "Buckets are index-based, not value-based.",
        "clinical_use_case": "Rough distribution shape.",
    },
    "mean": {
        "name": "Mean (Legacy)",
        "description": "Single mean value.",
        "required_columns": 1,
        "column_types": ["float", "integer"],
        "parameters": {},
        "estimated_seconds": 1,
        "approximation_warning": None,
        "clinical_use_case": "Simple aggregate.",
    },
    "multi_group_comparison": {
        "name": "Multi-Group Comparison",
        "description": "Mean and Std per group, pairwise differences; 2–4 groups (by index or mask columns).",
        "required_columns": 1,
        "column_types": ["float", "integer", "binary"],
        "parameters": {},
        "estimated_seconds": 5,
        "approximation_warning": "F-statistic is approximate; groups by segment or 0/1 masks.",
        "clinical_use_case": "Treatment vs Control vs Placebo.",
    },
    "logistic_regression_approx": {
        "name": "Logistic Regression (Approx)",
        "description": "Approximate coefficients for binary outcome; linear approximation only.",
        "required_columns": 2,
        "column_types": ["float", "integer", "binary"],
        "parameters": {},
        "estimated_seconds": 4,
        "approximation_warning": "For exploratory analysis only – not for clinical decisions.",
        "clinical_use_case": "Predict treatment response (yes/no) – screening only.",
    },
    "pearson_correlation_matrix": {
        "name": "Pearson Correlation Matrix",
        "description": "Full correlation matrix for 2–6 columns plus strongest correlations.",
        "required_columns": 2,
        "column_types": ["float", "integer"],
        "parameters": {},
        "estimated_seconds": 8,
        "approximation_warning": None,
        "clinical_use_case": "GWAS-style correlation between clinical markers.",
    },
    "survival_analysis_approx": {
        "name": "Survival Analysis (Approx)",
        "description": "Hazard rate, median survival approximation; no Kaplan-Meier (no sorting in HE).",
        "required_columns": 2,
        "column_types": ["float", "integer", "binary"],
        "parameters": {},
        "estimated_seconds": 3,
        "approximation_warning": "No true Kaplan-Meier; median and timepoints are approximations.",
        "clinical_use_case": "Survival in oncology studies – rough estimate only.",
    },
    "prevalence_and_risk": {
        "name": "Prevalence and Risk",
        "description": "Prevalence, Relative Risk, Odds Ratio (outcome and exposure 0/1).",
        "required_columns": 2,
        "column_types": ["binary", "integer"],
        "parameters": {},
        "estimated_seconds": 3,
        "approximation_warning": "CI requires decrypted counts for exact interval.",
        "clinical_use_case": "Epidemiology, risk factor analysis.",
    },
    "federated_mean_aggregation": {
        "name": "Federated Mean Aggregation",
        "description": "Weighted mean over value column; optional weight column. For multi-party meta-analysis.",
        "required_columns": 1,
        "column_types": ["float", "integer"],
        "parameters": {},
        "estimated_seconds": 2,
        "approximation_warning": None,
        "clinical_use_case": "Meta-analysis across institutions.",
    },
    "subgroup_analysis": {
        "name": "Subgroup Analysis",
        "description": "Mean and Std per subgroup; subgroups = binary mask columns (0/1).",
        "required_columns": 2,
        "column_types": ["float", "integer", "binary"],
        "parameters": {},
        "estimated_seconds": 6,
        "approximation_warning": "Thresholds must be precomputed as mask columns client-side.",
        "clinical_use_case": "Subgroup efficacy for regulatory submissions.",
    },
}
